# Generated by Django 5.2.4 on 2025-08-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='stock_keeping_unit',
        ),
    ]
