# Generated by Django 5.0 on 2024-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bad',
            field=models.BooleanField(default=False),
        ),
    ]
