# Generated by Django 5.2.4 on 2025-08-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_keeping_unit',
            new_name='sku',
        ),
    ]
