# Generated by Django 5.0 on 2024-01-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_is_bad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('contact', models.IntegerField(max_length=13)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='item.item')),
            ],
        ),
    ]
