# Generated by Django 5.0 on 2024-01-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
