# Generated by Django 5.0 on 2024-01-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_supplier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='qty_supplied',
            field=models.IntegerField(default=0),
        ),
    ]
