# Generated by Django 5.2.4 on 2025-08-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=10)),
                ('location', models.CharField(default='Port Harcourt, Nigeria', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='+2348074259720', max_length=15)),
                ('linkedIn_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
