# Generated by Django 5.2.4 on 2025-08-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='facebook_url',
            new_name='github_url',
        ),
    ]
