# Generated by Django 5.2.4 on 2025-08-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='write_up',
            new_name='about_text',
        ),
    ]
