# Generated by Django 5.2.4 on 2025-08-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_testimonial_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients'),
        ),
    ]
